In [1]:
import numpy as np

## 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
array1=np.zeros(10)  #Creating an array of size 10 with all zeros.
array1[4]=1  #Modifying the array to get fifth element as 1.
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [3]:
array2=np.arange(10,50)  #Creating an array from 10 to 49 with arange function of numpy.
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##  3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
array3=np.arange(0,9).reshape(3,3)   #Creating an 1D array with arange function then using reshape to convert it into a 3x3 matrix.
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
array4=np.array([1,2,0,0,4,0])   #Creating an array as given.
print(*array4.nonzero()[0],sep='\n')   #Using .nonzero() to get the indices with non zero values 
                                       #Slicing it with [0] to get just the list of indices
                                       #Using * at the beginning to uinpack this list
                                       #sep='\n' to print indices with non zeros on separate lines

0
1
4


In [6]:
# Or simply just
print(array4.nonzero())

(array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
array5=np.random.randn(10,10)   #Creating an 10x10 array/matrix with random values using .random.randn (if we want just positive values use .random.rand instead)
minimum_value=array5.min()    #Getting minimum value from the array using .min
maximum_value=array5.max()    #Getting maximum value from the array using .max
print('Minimum Value : %s \nMaximum Value : %s '%(minimum_value,maximum_value))

Minimum Value : -2.913031012532559 
Maximum Value : 2.4657041699572106 


## 6. Create a random vector of size 30 and find the mean value.

In [8]:
array6=np.random.random(30)    #Creating a random vector of size 30 using np.random.random
mean_value=array6.mean()       #Getting mean of array values using .mean
print('Mean Value : %s'%mean_value)

Mean Value : 0.5209481076449376
